### ISSUE TITLE
Sketch hijacking preview shortcut

### ISSUE THREAD

**Issue by jeremiahadkins** [marcisme/sketch-preview#17]
It seems Sketch natively hijacks the provided Preview shortcut (cmd+P). Is there a known workaround for this without having to go through the menu each time to refresh preview?

**Comment by marcisme** [comment]
Just to clarify, are you saying that nothing happens when you type ⌘P, or does it have to do with Sketch remaining the active application without bringing Skala Preview to the foreground? If the latter, that may be related to the most recent changes I made, but the preview image should still be getting updated.

Otherwise do you have any other plugins that might be using ⌘P? Sketch uses ^P for Show Pixels and ⌘⇧P for Page Setup, but I don't see anything that would conflict with ⌘P.

I think someone else was having trouble with they keyboard shortcut, and the problem was having multiple versions of the plugin installed, so you may want to check the plugins directory for old versions.

If none of that works, try changing the first line of the plugin to assign a different shortcut, and let me know if that doesn't work.

**Comment by jeremiahadkins** [comment]
It was another conflicting plugin. Thanks so much. Great work.

**Comment by marcisme** [comment]
Thanks. Glad you got it working.
