### ISSUE TITLE
CoreServicesUIAgent: Error -60005 creating authorization

### ISSUE THREAD

**Issue by sabihmir** [marcisme/sketch-preview#24]
Mac OSX Yosemite 10.10.4
Skala Preview 2.0
Skala View Android 1.2.2
Sketch 3.3.3 (12072)
Sketch Preview v0.8.0

Connects to Android app successfully, but as soon as this happens the Android app crashes. Console gives me an error:

CoreServicesUIAgent: Error -60005 creating authorization

Can't get it to display on Android device without the app crashing at all. Any idea? Thanks for working on this!

**Comment by marcisme** [comment]
Is the app that's crashing *Skala View Android*?

I'm not sure what that error means. I can find very few references to it on the web. It's possible it has something to do with sandboxing, but if the Android app is crashing, it may also be a result of that crash.

What happens if you manually export your mockup to an image and drag that onto the Skala Preview icon in the dock?

**Comment by marcisme** [comment]
I'm going to close this, as I don't have any Android devices to test with. Feel free to re-open the issue if you'd like further assistance.
