### ISSUE TITLE
Not previewing the correct artboard. 

### ISSUE THREAD

**Issue by Mediakik** [marcisme/sketch-preview#27]
I have 2 sketch files open, and I'm using the plugin. It was working just fine, but noticed today that it's loading an artboard from my other file for some reason, and not from the artboard I'm currently on?

**Comment by marcisme** [comment]
Are you using the released version (3.4) or the beta (3.4.1) ?

Do you happen to have any layers with Preview in their name?

Does this behavior persist if you close Sketch and open the files again? I just tried with three new documents, and I was able to switch between them and preview the expected artboard. It could be something with your specific documents, or Sketch could be getting into some weird state where it passes in the wrong document. It could also be a bug with the plugin, but Sketch passes the current document to the plugin, so that seems less likely.

**Comment by marcisme** [comment]
These issues should be fixed in 3.4.2. Let me know if that's not the case.

**Comment by nvasconcelos** [comment]
Hi @marcisme ,
I'm using the final version of Sketch 3.4.2 and I'm having the issue. 

The fact: I have more than 1 complex file opened, with several artboards and pages. 

It always previews an artboard from a different file, not the current one. 

The only error shown in Console.app when I hit cmd+P is: 
`11/24/15 4:10:07.682 PM CoreServicesUIAgent[14950]: Error -60005 creating authorization`

Thanks for the awesome plugin!

**Comment by marcisme** [comment]
Thanks for reporting this.

I've seen mention of one known remaining issue with the context returning the wrong document. Does [this branch](https://github.com/marcisme/sketch-preview/tree/fix-wrong-document-on-context) work for you? (note: the download link on the README won't work, you'll have to clone the repo.)

**Comment by marcisme** [comment]
@nvasconcelos beta 3.4.3 is out now, which is also supposed to address more of these context issues.

**Comment by marcisme** [comment]
The current artboard functionality should be working with the release version of Sketch now. Report back if this is still a problem.
