### ISSUE TITLE
Black screen on large height

### ISSUE THREAD

**Issue by MatejKustec** [marcisme/sketch-preview#32]
Hi, I have a problem with large height artboard, when I preview artboard it shows me black screen, if I reduce artboard height to smaller height it's working fine. 

I get this black screen on Skala View (android), on Skala Preview I see the image which should previewed.

**Comment by marcisme** [comment]
Do you know at what size the screen starts blacking out on Skala View? Someone else reported this a while back at around 1300 pixels, and I was unable to reproduce with Skala Preview. Unfortunately I no longer have any android devices to test Skala View on.

Since the image is displayed in Skala Preview but not Skala View, it seems like it might be an issue with Skala View. It would be helpful to know at what pixel hight the Skala View image goes black in order to follow up with bjango.

**Comment by MatejKustec** [comment]
I got black screen at 2049px height, so I'll also try to talk with bjango and see what they up to, it could be problem on their side.

**Comment by MatejKustec** [comment]
I got answer from bjango:
> We’re hoping to improve this in the future, but on some devices, the maximum GPU texture limits the image size. In this case, it seems like your device’s GPU texture limit is 2048 pixels (which is common). Sorry!

**Comment by marcisme** [comment]
Thanks for reporting back. That is unfortunate, but it's good to know about this limitation.
