### ISSUE TITLE
3.5 update issue

### ISSUE THREAD

**Issue by bfouillet** [marcisme/sketch-preview#34]
Hi,

I used to use your amazing Skala application on my phone and sketch. But it seems that Sketch 3.5 (I guess) makes skala view not recognize my macbook pro : "no computer available". It worked before the update even if I had to kill and relaunch the app to recognize my computer again.

The two devices are on the same wifi network. I work in a pretty large company and I have asked to the service in charge of network if they have changed some parameters on the network. They answer me no.

I have tried to reset the authorizations, but nothing changed.

Technical informations : I have a 5.1 Android phone with Skala View 2.0.3 and Sketch 3.5

Additional information : I am in the same position as : https://github.com/marcisme/sketch-preview/issues/33

Any Idea ? Thank you in advance.

Bertrand

**Comment by marcisme** [comment]
Thanks! I'm glad the plugin has been useful to you.

Unfortunately it sounds like the issue is with communication between Skala Preview and Skala View, so I'm surprised that Sketch 3.5 is behaving differently than previous versions.

You may want to try reinstalling the [Skala Preview](https://bjango.com/mac/skalapreview/) application and testing using that directly. The plugin basically just exports the current artboard to a temp directory and opens that file in Skala Preview, so if you can get it working on its own, the plugin should work.

There's also some [help](https://bjango.com/help/skalapreview/gettingstarted/) over on Bjango's site. In particular you may want to run the [ports](https://bjango.com/help/skalapreview/ports/) page by your admins. It's possible they missed something or didn't know what specifically to look for.

**Comment by bfouillet** [comment]
Thank you for your help.

Your plugin works. When I "cmd + P" an artboard it is refresh in Skala preview on my mac.

But as you said there is no communication between the app and the software on my mac...

I am going to try to find an answer on Bjango website.

Keep in touch,

Bertrand

**Comment by bfouillet** [comment]
Ok I found a solution. 

If you activate your mac firewall and add skala preview to the list : it works like a charm :+1: 

Hope it will help someone else :)

Thanks again
![capture d ecran 2016-02-19 a 10 38 48](https://cloud.githubusercontent.com/assets/17310968/13171803/1636ee20-d6f5-11e5-8adb-8e55847173b5.png)

**Comment by marcisme** [comment]
Awesome. I'm glad you got it working.

Thanks for sharing the solution!
