### ISSUE TITLE
Sketch Artboard no longer working

### ISSUE THREAD

**Issue by kerbelda** [marcisme/sketch-preview#44]
I can drag images to Skala Preview; however, I can't use Command + P to preview artboards from sketch anymore. It gets stuck on a black 1x1 square ([see screenshot](https://imgur.com/a/19C0K)). 

I'm using the latest version, 207, and macOS High Sierra 10.13.2.

**Comment by marcisme** [comment]
@kerbelda Do you have a slice named "Preview"? There's a legacy feature that exports a slice with that name if it's found, so that may be overriding your selected Artboard.

If that's the case, your best options are to change the name of that slice, or change [this line](https://github.com/marcisme/sketch-preview/blob/master/SketchPreview.sketchplugin/Contents/Sketch/Preview.sketchscript#L29) in the plugin bundle to have a different name.

Let me know if that fixes it. I may remove that feature or change the layer name to something less general because I don't think anyone uses it anymore.

**Comment by marcisme** [comment]
I'm going to assume this is working now. Let me know if that's not the case.

**Comment by nigharsh** [comment]
Still not working

**Comment by marcisme** [comment]
@nigharsh Were you experiencing the same issue as the OP?

If so, the log output described in the [troubleshooting](https://github.com/marcisme/sketch-preview#troubleshooting) section would be helpful. Otherwise please provide some specifics of how you're using the plugin.
